In [1]:
import pandas as pd
import numpy as np

In [16]:
# read in csv files

# crimes data
crimes_la = pd.read_csv('crime_data/crimes_la.csv')
crimes_ventura = pd.read_csv('crime_data/crimes_ventura.csv')
crimes_orange = pd.read_csv('crime_data/crimes_orange.csv')

# personal justice data
criminal_justice_la = pd.read_csv('criminal_justice_data/criminal_justice_la.csv')
criminal_justice_ventura = pd.read_csv('criminal_justice_data/criminal_justice_ventura.csv')
criminal_justice_orange = pd.read_csv('criminal_justice_data/criminal_justice_orange.csv')

In [17]:
# Rename the columns
crimes_la.columns = ['Crime Types', 'LA County']
crimes_ventura.columns = ['Crime Types', 'Ventura County']
crimes_orange.columns = ['Crime Types', 'Orange County']

# Transpose the dataframes. First set the index
crimes_la.set_index('Crime Types',inplace=True)
crimes_ventura.set_index('Crime Types',inplace=True)
crimes_orange.set_index('Crime Types',inplace=True)

# Tranpose
crimes_la = crimes_la.transpose()
crimes_ventura = crimes_ventura.transpose()
crimes_orange = crimes_orange.transpose()

In [18]:
# Merge the crime dataframes for all three counties
crimes_df = [crimes_la, crimes_ventura, crimes_orange]
crimes_df = pd.concat(crimes_df)
crimes_df = crimes_df.rename_axis(None, axis=1).rename_axis('', axis=0)
crimes_df

,Crimes,Violent Crimes,Homicide,Rape (Forcible Rape prior to 2014),Rape,Attempted Rape,Robbery,Weapon,Firearm,Knife or Cutting Instrument,...,Other,Value,Over $400,$200 through $400,$50 through $199,Under $50,Arson,Structural Property,Mobile Property,Other Property
,,,,,,,,,,,,,,,,,,,,,
LA County,NaN,"56,351",622,"4,153","3,913",240,"20,147",NaN,"5,410","1,953",...,"25,229",NaN,"66,520","23,271","28,402","39,617","2,360",558,570,"1,232"
Ventura County,NaN,"2,192",31,269,258,11,725,NaN,158,162,...,"2,064",NaN,"4,002","1,803","2,503","3,547",113,34,32,47
Orange County,NaN,"7,275",57,810,769,41,"2,136",NaN,465,287,...,"9,841",NaN,"18,006","7,113","8,683","12,705",269,87,53,129

In [19]:
# Do the same thing for the personal justice data

# Rename the columns
criminal_justice_la.columns = ['Personal Justice #', 'LA County']
criminal_justice_ventura.columns = ['Personal Justice #', 'Ventura County']
criminal_justice_orange.columns = ['Personal Justice #', 'Orange County']

# Transpose the dataframes. First set the index
criminal_justice_la.set_index('Personal Justice #',inplace=True)
criminal_justice_ventura.set_index('Personal Justice #',inplace=True)
criminal_justice_orange.set_index('Personal Justice #',inplace=True)

# Tranpose
criminal_justice_la = criminal_justice_la.transpose()
criminal_justice_ventura = criminal_justice_ventura.transpose()
criminal_justice_orange = criminal_justice_orange.transpose()

In [20]:
# Merge the personal justice dataframes for all three counties
personal_justice_df = [criminal_justice_la, criminal_justice_ventura, criminal_justice_orange]
personal_justice_df = pd.concat(personal_justice_df)
personal_justice_df = personal_justice_df.rename_axis(None, axis=1).rename_axis('', axis=0)
personal_justice_df

,Total,Law Enforcement,Sworn,Civilian,Police Dept,Sworn,Civilian,Sheriff's Dept,Sworn,Civilian,...,Clerical,Other,Public Defense,Attorneys,Investigators,Clerical,Other,Probation Dept,Probation Officers,Other
,,,,,,,,,,,,,,,,,,,,,
LA County,"44,799","36,253","23,734","12,519","19,219","14,231","4,988","16,721","9,316","7,405",...,476,337,"1,040",688,73,157,122,"5,466","4,036","1,430"
Ventura County,"2,787","2,037","1,312",725,744,525,219,"1,247",756,491,...,47,54,103,59,15,15,14,390,303,87
Orange County,"9,759","7,439","4,307","3,132","3,718","2,495","1,223","3,622","1,745","1,877",...,120,192,385,202,74,57,52,"1,175",815,360

In [ ]:
# Crimes Dataframe Initial EDA

In [21]:
crimes_df.shape

(3, 64)

In [22]:
crimes_df.columns

Index(['Crimes', 'Violent Crimes', 'Homicide',
       'Rape (Forcible Rape prior to 2014)', 'Rape', 'Attempted Rape',
       'Robbery', 'Weapon', 'Firearm', 'Knife or Cutting Instrument',
       'Other Weapon', 'Strong-Arm', 'Location', 'Highway', 'Commercial',
       'Gas Station', 'Convenience Store', 'Residence', 'Bank',
       'Miscellaneous', 'Aggravated Assault', 'Weapon', 'Firearm',
       'Knife or Cutting Instrument', 'Other Weapon', 'Hands  Fists  Feet',
       'Property Crimes', 'Burglary', 'Means of Entry', 'Forcible Entry',
       'No Force', 'Location / Time', 'Residence', 'Night', 'Day', 'Unknown',
       'Non-Residence', 'Night', 'Day', 'Unknown', 'Motor Vehicle Theft',
       'Automotive', 'Trucks and Buses', 'Other', 'Larceny-Theft', 'Type',
       'Pocket-Picking', 'Purse-Snatching', 'Shoplifting',
       'From Motor Vehicle', 'Motor Vehicle Accessories', 'Bicycles',
       'From Building', 'Coin Operated Machine', 'Other', 'Value', 'Over $400',
       '$200 through $400', '$50 through $199', 'Under $50', 'Arson',
       'Structural Property', 'Mobile Property', 'Other Property'],
      dtype='object')

In [23]:
crimes_df_undetailed = crimes_df[['Violent Crimes','Homicide', 'Rape (Forcible Rape prior to 2014)', 'Robbery', 'Aggravated Assault', 'Property Crimes', 'Burglary', 'Motor Vehicle Theft', 'Larceny-Theft', 'Arson']]

In [24]:
crimes_df_undetailed

,Violent Crimes,Homicide,Rape (Forcible Rape prior to 2014),Robbery,Aggravated Assault,Property Crimes,Burglary,Motor Vehicle Theft,Larceny-Theft,Arson
,,,,,,,,,,
LA County,"56,351",622,"4,153","20,147","31,429","252,224","46,918","47,496","157,810","2,360"
Ventura County,"2,192",31,269,725,"1,167","16,415","2,910","1,650","11,855",113
Orange County,"7,275",57,810,"2,136","4,272","66,054","11,025","8,522","46,507",269

In [29]:
personal_justice_df.columns

Index(['Total', 'Law Enforcement', 'Sworn', 'Civilian', 'Police Dept', 'Sworn',
       'Civilian', 'Sheriff's Dept', 'Sworn', 'Civilian', 'CA Highway Patrol',
       'Sworn', 'Civilian', 'Other', 'Sworn', 'Civilian', 'Prosecution',
       'Attorneys', 'Investigators', 'Clerical', 'Other', 'Public Defense',
       'Attorneys', 'Investigators', 'Clerical', 'Other', 'Probation Dept',
       'Probation Officers', 'Other'],
      dtype='object')

In [34]:
personal_justice_df = personal_justice_df[personal_justice_df.columns[~personal_justice_df.columns.isin(['Total', 'Sworn', 'Civilian', 'Other', 'Attorneys', 'Investigators', 'Clerical', 'Probation Officers', 'CA Highway Patrol'])]]

In [36]:
personal_justice_df

,Law Enforcement,Police Dept,Sheriff's Dept,Prosecution,Public Defense,Probation Dept
,,,,,,
LA County,"36,253","19,219","16,721","2,040","1,040","5,466"
Ventura County,"2,037",744,"1,247",257,103,390
Orange County,"7,439","3,718","3,622",760,385,"1,175"

In [41]:
full_crime_data = pd.concat([crimes_df_undetailed, personal_justice_df], axis=1)
full_crime_data.to_csv('full_crime_data.csv', encoding='utf-8', index=True)

In [42]:
full_crime_data

,Violent Crimes,Homicide,Rape (Forcible Rape prior to 2014),Robbery,Aggravated Assault,Property Crimes,Burglary,Motor Vehicle Theft,Larceny-Theft,Arson,Law Enforcement,Police Dept,Sheriff's Dept,Prosecution,Public Defense,Probation Dept
,,,,,,,,,,,,,,,,
LA County,"56,351",622,"4,153","20,147","31,429","252,224","46,918","47,496","157,810","2,360","36,253","19,219","16,721","2,040","1,040","5,466"
Ventura County,"2,192",31,269,725,"1,167","16,415","2,910","1,650","11,855",113,"2,037",744,"1,247",257,103,390
Orange County,"7,275",57,810,"2,136","4,272","66,054","11,025","8,522","46,507",269,"7,439","3,718","3,622",760,385,"1,175"